import { Outfit } from "next/font/google";
import "./globals.css";
import { Toaster } from "@/components/ui/toaster";
import Provider from "./components/Provider";

const outfit = Outfit({ subsets: ["latin"] });
export const metadata = {
  title: "Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={outfit.className}>
        <Provider>{children}</Provider>
        <Toaster />
      </body>
    </html>
  );
}
